name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Stop Backend App Pool
        run: |
          Import-Module WebAdministration

          $pool = Get-WebAppPoolState -Name "AquaticFishECommercePool"

          if ($pool.Value -eq "Started") {
              Stop-WebAppPool -Name "AquaticFishECommercePool"
              Start-Sleep -Seconds 2
          }
          else {
              Write-Host "App Pool is already stopped."
          }

      - name: Publish
        run: |
          dotnet publish .\src\AquaticFishECommerce.API\AquaticFishECommerce.API.csproj `
            -c Release `
            -o C:\inetpub\AquaticFishECommerce

      - name: Start Backend App Pool
        run: |
          Import-Module WebAdministration

          $pool = Get-WebAppPoolState -Name "AquaticFishECommercePool"

          if ($pool.Value -ne "Started") {
              Start-WebAppPool -Name "AquaticFishECommercePool"
          }
          else {
              Write-Host "App Pool is already running."
          }
